export const EQ_PRESETS = [
  {
    id: "voice-presence",
    name: "Voice Presence",
    description: "Enhances vocal clarity and intelligibility for spoken word recordings",
    category: "voice",
    bands: [
      { frequency: 80, gain: -6, q: 0.7, type: "highpass" },
      { frequency: 300, gain: -3, q: 1.4, type: "peaking" },
      { frequency: 1200, gain: 2, q: 1.2, type: "peaking" },
      { frequency: 3500, gain: 4, q: 1.0, type: "peaking" },
      { frequency: 7000, gain: 2, q: 1.4, type: "peaking" },
      { frequency: 12000, gain: 3, q: 0.9, type: "highshelf" },
    ],
  },
  {
    id: "voice-warmth",
    name: "Voice Warmth",
    description: "Adds warmth and body to thin or harsh vocal recordings",
    category: "voice",
    bands: [
      { frequency: 100, gain: -4, q: 0.8, type: "highpass" },
      { frequency: 200, gain: 3, q: 1.0, type: "peaking" },
      { frequency: 400, gain: 1.5, q: 1.2, type: "peaking" },
      { frequency: 3000, gain: -1.5, q: 1.0, type: "peaking" },
      { frequency: 8000, gain: -2, q: 0.9, type: "peaking" },
      { frequency: 14000, gain: 1, q: 0.8, type: "highshelf" },
    ],
  },
  {
    id: "voice-broadcast",
    name: "Broadcast Voice",
    description: "Classic radio broadcast EQ for authoritative, present vocal sound",
    category: "broadcast",
    bands: [
      { frequency: 120, gain: -8, q: 0.7, type: "highpass" },
      { frequency: 250, gain: -2, q: 1.5, type: "peaking" },
      { frequency: 1500, gain: 3, q: 0.9, type: "peaking" },
      { frequency: 4000, gain: 5, q: 1.1, type: "peaking" },
      { frequency: 10000, gain: 4, q: 0.8, type: "highshelf" },
    ],
  },
  {
    id: "music-bright",
    name: "Music Bright",
    description: "Adds sparkle and airiness to music mixes that feel dull",
    category: "music",
    bands: [
      { frequency: 60, gain: 2, q: 0.9, type: "lowshelf" },
      { frequency: 400, gain: -2, q: 1.5, type: "peaking" },
      { frequency: 2000, gain: 1.5, q: 1.0, type: "peaking" },
      { frequency: 8000, gain: 3, q: 0.9, type: "peaking" },
      { frequency: 16000, gain: 4, q: 0.8, type: "highshelf" },
    ],
  },
  {
    id: "music-warm",
    name: "Music Warm",
    description: "Adds vintage warmth and fullness to modern recordings",
    category: "music",
    bands: [
      { frequency: 80, gain: 3, q: 0.8, type: "lowshelf" },
      { frequency: 250, gain: 2, q: 1.2, type: "peaking" },
      { frequency: 1200, gain: -1, q: 1.5, type: "peaking" },
      { frequency: 5000, gain: -2, q: 1.2, type: "peaking" },
      { frequency: 12000, gain: -1, q: 0.9, type: "highshelf" },
    ],
  },
  {
    id: "music-balanced",
    name: "Music Balanced",
    description: "Natural, transparent enhancement that preserves the original mix character",
    category: "music",
    bands: [
      { frequency: 50, gain: 1, q: 0.8, type: "lowshelf" },
      { frequency: 300, gain: -1, q: 1.5, type: "peaking" },
      { frequency: 1000, gain: 0.5, q: 1.0, type: "peaking" },
      { frequency: 4000, gain: 1, q: 1.2, type: "peaking" },
      { frequency: 15000, gain: 1.5, q: 0.9, type: "highshelf" },
    ],
  },
  {
    id: "podcast-clarity",
    name: "Podcast Clarity",
    description: "Optimized EQ for podcast voice clarity and intelligibility",
    category: "podcast",
    bands: [
      { frequency: 100, gain: -6, q: 0.7, type: "highpass" },
      { frequency: 350, gain: -3, q: 1.4, type: "peaking" },
      { frequency: 1200, gain: 2, q: 1.0, type: "peaking" },
      { frequency: 3000, gain: 3, q: 1.1, type: "peaking" },
      { frequency: 8000, gain: 2, q: 1.0, type: "peaking" },
    ],
  },
  {
    id: "podcast-warmth",
    name: "Podcast Warmth",
    description: "Warm, intimate podcast sound for storytelling and interview formats",
    category: "podcast",
    bands: [
      { frequency: 120, gain: -8, q: 0.8, type: "highpass" },
      { frequency: 180, gain: 3, q: 1.2, type: "peaking" },
      { frequency: 300, gain: 1.5, q: 1.5, type: "peaking" },
      { frequency: 2500, gain: 2, q: 1.0, type: "peaking" },
      { frequency: 10000, gain: 1, q: 0.9, type: "highshelf" },
    ],
  },
  {
    id: "film-dialogue",
    name: "Film Dialogue",
    description: "Crisp, clear dialogue EQ for film and television production",
    category: "film",
    bands: [
      { frequency: 80, gain: -10, q: 0.7, type: "highpass" },
      { frequency: 300, gain: -2, q: 1.8, type: "peaking" },
      { frequency: 900, gain: 1.5, q: 1.2, type: "peaking" },
      { frequency: 3500, gain: 4, q: 1.0, type: "peaking" },
      { frequency: 9000, gain: 2, q: 0.9, type: "peaking" },
      { frequency: 18000, gain: -3, q: 0.7, type: "highshelf" },
    ],
  },
  {
    id: "film-score",
    name: "Film Score",
    description: "Cinematic orchestral enhancement for film and game scores",
    category: "film",
    bands: [
      { frequency: 40, gain: 2, q: 0.8, type: "lowshelf" },
      { frequency: 200, gain: -1, q: 2.0, type: "peaking" },
      { frequency: 600, gain: 1, q: 1.4, type: "peaking" },
      { frequency: 3000, gain: 1.5, q: 1.0, type: "peaking" },
      { frequency: 10000, gain: 2, q: 0.9, type: "highshelf" },
    ],
  },
  {
    id: "restoration-old",
    name: "Old Recording Restore",
    description: "Restores clarity and removes muddiness from vintage or degraded recordings",
    category: "restoration",
    bands: [
      { frequency: 60, gain: -8, q: 0.7, type: "highpass" },
      { frequency: 200, gain: -4, q: 1.5, type: "peaking" },
      { frequency: 600, gain: -3, q: 1.8, type: "peaking" },
      { frequency: 3000, gain: 4, q: 1.0, type: "peaking" },
      { frequency: 6000, gain: 5, q: 1.1, type: "peaking" },
      { frequency: 14000, gain: -6, q: 0.8, type: "highshelf" },
    ],
  },
  {
    id: "restoration-room",
    name: "Room Correction",
    description: "Neutralizes room resonances and acoustic coloration",
    category: "restoration",
    bands: [
      { frequency: 250, gain: -4, q: 2.0, type: "peaking" },
      { frequency: 500, gain: -3, q: 2.5, type: "peaking" },
      { frequency: 1000, gain: -2, q: 2.0, type: "peaking" },
      { frequency: 4000, gain: 2, q: 1.5, type: "peaking" },
      { frequency: 10000, gain: 3, q: 1.0, type: "highshelf" },
    ],
  },
];

export const MASTERING_GENRES = [
  {
    id: "pop",
    name: "Pop",
    description: "Polished, radio-ready sound with punchy dynamics and sparkling highs",
    targetLufs: -14,
    compressionAmount: 0.65,
    dynamicEqAmount: 0.55,
    exciterAmount: 0.45,
    character: "Bright & Punchy",
  },
  {
    id: "rock",
    name: "Rock",
    description: "Powerful, energetic mastering with presence and weight",
    targetLufs: -12,
    compressionAmount: 0.70,
    dynamicEqAmount: 0.50,
    exciterAmount: 0.40,
    character: "Powerful & Present",
  },
  {
    id: "hip-hop",
    name: "Hip-Hop / Trap",
    description: "Deep bass, punchy kicks, and crisp high-end for streaming",
    targetLufs: -13,
    compressionAmount: 0.60,
    dynamicEqAmount: 0.65,
    exciterAmount: 0.50,
    character: "Deep & Crisp",
  },
  {
    id: "electronic",
    name: "Electronic / EDM",
    description: "Wide stereo image, tight transients, and extended high-end",
    targetLufs: -10,
    compressionAmount: 0.75,
    dynamicEqAmount: 0.70,
    exciterAmount: 0.55,
    character: "Wide & Energetic",
  },
  {
    id: "jazz",
    name: "Jazz",
    description: "Natural, dynamic mastering that preserves the acoustic character",
    targetLufs: -18,
    compressionAmount: 0.25,
    dynamicEqAmount: 0.30,
    exciterAmount: 0.20,
    character: "Natural & Dynamic",
  },
  {
    id: "classical",
    name: "Classical / Orchestral",
    description: "Transparent mastering with full dynamic range and spatial depth",
    targetLufs: -23,
    compressionAmount: 0.10,
    dynamicEqAmount: 0.20,
    exciterAmount: 0.15,
    character: "Transparent & Spacious",
  },
  {
    id: "country",
    name: "Country",
    description: "Warm, open sound with presence and natural instrument separation",
    targetLufs: -15,
    compressionAmount: 0.45,
    dynamicEqAmount: 0.40,
    exciterAmount: 0.35,
    character: "Warm & Open",
  },
  {
    id: "rnb-soul",
    name: "R&B / Soul",
    description: "Smooth, warm low-end with silky highs and intimate vocals",
    targetLufs: -14,
    compressionAmount: 0.55,
    dynamicEqAmount: 0.50,
    exciterAmount: 0.40,
    character: "Smooth & Warm",
  },
  {
    id: "metal",
    name: "Metal / Hard Rock",
    description: "Heavy, aggressive mastering with maximum density and attack",
    targetLufs: -10,
    compressionAmount: 0.85,
    dynamicEqAmount: 0.60,
    exciterAmount: 0.35,
    character: "Dense & Aggressive",
  },
  {
    id: "acoustic",
    name: "Acoustic / Folk",
    description: "Honest, natural mastering that lets the performance speak",
    targetLufs: -18,
    compressionAmount: 0.20,
    dynamicEqAmount: 0.25,
    exciterAmount: 0.25,
    character: "Honest & Natural",
  },
  {
    id: "podcast",
    name: "Podcast / Spoken Word",
    description: "Clear, intelligible voice mastering optimized for mobile listening",
    targetLufs: -16,
    compressionAmount: 0.70,
    dynamicEqAmount: 0.75,
    exciterAmount: 0.30,
    character: "Clear & Consistent",
  },
  {
    id: "film-score",
    name: "Film Score / Cinematic",
    description: "Expansive, dramatic mastering for maximum emotional impact",
    targetLufs: -23,
    compressionAmount: 0.15,
    dynamicEqAmount: 0.35,
    exciterAmount: 0.40,
    character: "Expansive & Dramatic",
  },
  {
    id: "lofi",
    name: "Lo-Fi / Chill",
    description: "Warm, slightly compressed vintage character for atmospheric listening",
    targetLufs: -18,
    compressionAmount: 0.50,
    dynamicEqAmount: 0.30,
    exciterAmount: 0.20,
    character: "Warm & Nostalgic",
  },
  {
    id: "ambient",
    name: "Ambient / Drone",
    description: "Spacious, ethereal mastering with rich harmonic depth",
    targetLufs: -20,
    compressionAmount: 0.20,
    dynamicEqAmount: 0.40,
    exciterAmount: 0.50,
    character: "Ethereal & Spacious",
  },
];
